### ISSUE TITLE
webpack parser error on index.css

### ISSUE THREAD

**Issue by iamromuald** [tastejs/todomvc-app-css#23]
Hello I've met an error using webpack bundling tool.
It's a simple CSS syntax error. Will reference the issue in a PR that solved the trick for me.

```
ERROR in ./~/todomvc-app-css/index.css
Module parse failed: /Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/todomvc-app-css/index.css Unexpected token (2:5)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:5)
    at Parser.pp$4.raise (/Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseTopLevel (/Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/esensory/ESensory/dev/playground/redux-todomvc/node_modules/webpack/lib/NormalModule.js:104:16)
 @ ./src/index.jsx 19:0-52
```

**Comment by sindresorhus** [comment]
https://github.com/tastejs/todomvc-app-css/pull/24#issuecomment-246630471
